#!/usr/bin/env python3
"""
Setup script for Recombee .env file
This script helps you create a .env file with your Recombee credentials.
"""

import os
import shutil

def setup_env_file():
    """
    Help user create a .env file with Recombee credentials.
    """
    print("🔧 RECOMBEE .ENV SETUP")
    print("="*50)
    print()
    
    # Check if .env already exists
    if os.path.exists('.env'):
        print("⚠️  .env file already exists!")
        overwrite = input("Do you want to overwrite it? (y/n): ").lower().strip()
        if overwrite not in ['y', 'yes']:
            print("Setup cancelled.")
            return
    
    print("Let's create your .env file with Recombee credentials.")
    print("You can find these in your Recombee admin panel under Integration > Catalog Feed")
    print()
    
    # Get credentials from user
    url = input("Enter your Recombee API URL (e.g., https://your-database.recombee.com): ").strip()
    database_id = input("Enter your Database ID: ").strip()
    secret_token = input("Enter your Secret Token: ").strip()
    batch_size = input("Enter batch size (default: 100): ").strip() or "100"
    
    if not all([url, database_id, secret_token]):
        print("❌ Missing required credentials. Setup cancelled.")
        return
    
    # Create .env file
    env_content = f"""# Recombee API Configuration
# Generated by setup script

# Your Recombee API URL
RECOMBEE_URL={url}

# Your Recombee Database ID
RECOMBEE_DATABASE_ID={database_id}

# Your Recombee Secret Token
RECOMBEE_SECRET_TOKEN={secret_token}

# Batch size for API requests
RECOMBEE_BATCH_SIZE={batch_size}
"""
    
    try:
        with open('.env', 'w') as f:
            f.write(env_content)
        
        print("\n✅ .env file created successfully!")
        print("You can now run: python3 lab1.py")
        print()
        print("🔒 Security reminder:")
        print("- Never commit .env file to version control")
        print("- Keep your secret token secure")
        
    except Exception as e:
        print(f"❌ Error creating .env file: {e}")

if __name__ == "__main__":
    setup_env_file()
